### ISSUE TITLE
./set_pipeline_crawler.sh issue

### ISSUE THREAD

**Issue by dashaun** [CloudPipelines/concourse#8]
After "it works on my machine" I tried to walk @seanbot2000 through my process.

1.  forked the repo and made a local clone
2.  Created a .envrc that has all of the required environment variables
3.  Created a credentials.yml from the sample for cf
4.  Ran the ./set_pipeline_crawler.sh

Expected to get pipelines in concourse but got this output:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/Users/sean/Projects/concourse/src/pipeline/build/groovy-2.5.2/lib/groovy-2.5.2.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Caught: BUG! exception in phase ‘semantic analysis’ in source unit ‘/Users/sean/Projects/concourse/src/pipeline/crawler.groovy’ null
BUG! exception in phase ‘semantic analysis’ in source unit ‘/Users/sean/Projects/concourse/src/pipeline/crawler.groovy’ null
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caused by: java.lang.UnsupportedOperationException
    at groovyjarjarasm.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
    at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:651)
    at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:391)
    ... 3 more.
```

**Comment by marcingrzejszczak** [comment]
Should be fixed via https://github.com/CloudPipelines/concourse/commit/b1e721011dd142f28a03899cacc8c5ba95b886dc
